spring:
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5435/task_db
    username: postgres
    password: postgres
    hikari:
      schema: task_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_app_schema
      connection-timeout: 10000


app:
  upload:
    path: src/main/resources/upload_covers/
  jwt:
    secret: "secretKey"
    tokenExpiration: 30h
    refreshTokenExpiration: 30h
